name: Run Tests

on:
  push:
    paths:
      - src/output/*.feature

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version here

      - name: Install dependencies
        run: |
          pip install behave selenium  # Adjust based on your needs

      - name: Run Behave Tests
        run: |
          behave src/output  # Adjust the path to your feature files
